using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Minecraft_Tools
{
    internal static class Minecraft_Splashes
    {
        internal static readonly string[] Matriz_Líneas = new string[]
        {
            "missingno", // Default value extracted from the Minecraft 1.12 source code. This name was also used by a Pokémon on it's first games, but it was shown probably as a game bug.
            "Merry X-mas!", // Shown on 24th of February.
            "Happy new year!", // Shown on 1st of January.
            "OOoooOOOoooo! Spooky!", // Shown on 31st of October.
            "As seen on TV!",
            "Awesome!",
            "100% pure!",
            "May contain nuts!",
            "More polygons!",
            "Sexy!",
            "Limited edition!",
            "Flashing letters!",
            "Made by Notch!",
            "It's here!",
            "Best in class!",
            "It's finished!",
            "Kind of dragon free!",
            "Excitement!",
            "More than 500 sold!",
            "One of a kind!",
            "Heaps of hits on YouTube!",
            "Indev!",
            "Spiders everywhere!",
            "Check it out!",
            "Holy cow, man!",
            "It's a game!",
            "Made in Sweden!",
            "Uses LWJGL!",
            "Reticulating splines!",
            "Minecraft!",
            "Yaaay!",
            "Singleplayer!",
            "Keyboard compatible!",
            "Undocumented!",
            "Ingots!",
            "Exploding creepers!",
            "That's no moon!",
            "l33t!",
            "Create!",
            "Survive!",
            "Dungeon!",
            "Exclusive!",
            "The bee's knees!",
            "Down with O.P.P.!",
            "Closed source!",
            "Classy!",
            "Wow!",
            "Not on steam!",
            "Oh man!",
            "Awesome community!",
            "Pixels!",
            "Teetsuuuuoooo!",
            "Kaaneeeedaaaa!",
            "Now with difficulty!",
            "Enhanced!",
            "90% bug free!",
            "Pretty!",
            "12 herbs and spices!",
            "Fat free!",
            "Absolutely no memes!",
            "Free dental!",
            "Ask your doctor!",
            "Minors welcome!",
            "Cloud computing!",
            "Legal in Finland!",
            "Hard to label!",
            "Technically good!",
            "Bringing home the bacon!",
            "Indie!",
            "GOTY!",
            "Ceci n'est pas une title screen!",
            "Euclidian!",
            "Now in 3D!",
            "Inspirational!",
            "Herregud!",
            "Complex cellular automata!",
            "Yes, sir!",
            "Played by cowboys!",
            "OpenGL 2.1 (if supported)!",
            "Thousands of colors!",
            "Try it!",
            "Age of Wonders is better!",
            "Try the mushroom stew!",
            "Sensational!",
            "Hot tamale, hot hot tamale!",
            "Play him off, keyboard cat!",
            "Guaranteed!",
            "Macroscopic!",
            "Bring it on!",
            "Random splash!",
            "Call your mother!",
            "Monster infighting!",
            "Loved by millions!",
            "Ultimate edition!",
            "Freaky!",
            "You've got a brand new key!",
            "Water proof!",
            "Uninflammable!",
            "Whoa, dude!",
            "All inclusive!",
            "Tell your friends!",
            "NP is not in P!",
            "Music by C418!",
            "Livestreamed!",
            "Haunted!",
            "Polynomial!",
            "Terrestrial!",
            "All is full of love!",
            "Full of stars!",
            "Scientific!",
            "Not as cool as Spock!",
            "Collaborate and listen!",
            "Never dig down!",
            "Take frequent breaks!",
            "Not linear!",
            "Han shot first!",
            "Nice to meet you!",
            "Buckets of lava!",
            "Ride the pig!",
            "Larger than Earth!",
            "sqrt(-1) love you!",
            "Phobos anomaly!",
            "Punching wood!",
            "Falling off cliffs!",
            "1% sugar!",
            "150% hyperbole!",
            "Synecdoche!",
            "Let's danec!",
            "Seecret Friday update!",
            "Reference implementation!",
            "Lewd with two dudes with food!",
            "Kiss the sky!",
            "20 GOTO 10!",
            "Verlet intregration!",
            "Peter Griffin!",
            "Do not distribute!",
            "Cogito ergo sum!",
            "4815162342 lines of code!",
            "A skeleton popped out!",
            "The Work of Notch!",
            "The sum of its parts!",
            "BTAF used to be good!",
            "I miss ADOM!",
            "umop-apisdn!",
            "OICU812!",
            "Bring me Ray Cokes!",
            "Finger-licking!",
            "Thematic!",
            "Pneumatic!",
            "Sublime!",
            "Octagonal!",
            "Une baguette!",
            "Gargamel plays it!",
            "Rita is the new top dog!",
            "SWM forever!",
            "Representing Edsbyn!",
            "Matt Damon!",
            "Supercalifragilisticexpialidocious!",
            "Consummate V's!",
            "Cow Tools!",
            "Double buffered!",
            "Fan fiction!",
            "Flaxkikare!",
            "Jason! Jason! Jason!",
            "Hotter than the sun!",
            "Internet enabled!",
            "Autonomous!",
            "Engage!",
            "Fantasy!",
            "DRR! DRR! DRR!",
            "Kick it root down!",
            "Regional resources!",
            "Woo, facepunch!",
            "Woo, somethingawful!",
            "Woo, /v/!",
            "Woo, tigsource!",
            "Woo, minecraftforum!",
            "Woo, worldofminecraft!",
            "Woo, reddit!",
            "Woo, 2pp!",
            "Google anlyticsed!",
            "Now supports åäö!",
            "Give us Gordon!",
            "Tip your waiter!",
            "Very fun!",
            "12345 is a bad password!",
            "Vote for net neutrality!",
            "Lives in a pineapple under the sea!",
            "MAP11 has two names!",
            "Omnipotent!",
            "Gasp!",
            "...!",
            "Bees, bees, bees, bees!",
            "Jag känner en bot!",
            "This text is hard to read if you play the game at the default resolution, but at 1080p it's fine!",
            "Haha, LOL!",
            "Hampsterdance!",
            "Switches and ores!",
            "Menger sponge!",
            "idspispopd!",
            "Eple (original edit)!",
            "So fresh, so clean!",
            "Slow acting portals!",
            "Try the Nether!",
            "Don't look directly at the bugs!",
            "Oh, ok, Pigmen!",
            "Finally with ladders!",
            "Scary!",
            "Play Minecraft, Watch Topgear, Get Pig!",
            "Twittered about!",
            "Jump up, jump up, and get down!",
            "Joel is neat!",
            "A riddle, wrapped in a mystery!",
            "Huge tracts of land!",
            "Welcome to your Doom!",
            "Stay a while, stay forever!",
            "Stay a while and listen!",
            "Treatment for your rash!",
            "\"Autological\" is!",
            "Information wants to be free!",
            "\"Almost never\" is an interesting concept!",
            "Lots of truthiness!",
            "The creeper is a spy!",
            "Turing complete!",
            "It's groundbreaking!",
            "Let our battle's begin!",
            "The sky is the limit!",
            "Jeb has amazing hair!",
            "Ryan also has amazing hair!",
            "Casual gaming!",
            "Undefeated!",
            "Kinda like Lemmings!",
            "Follow the train, CJ!",
            "Leveraging synergy!",
            "This message will never appear on the splash screen, isn't that weird?",
            "DungeonQuest is unfair!",
            "110813!",
            "90210!",
            "Check out the far lands!",
            "Tyrion would love it!",
            "Also try VVVVVV!",
            "Also try Super Meat Boy!",
            "Also try Terraria!",
            "Also try Mount And Blade!",
            "Also try Project Zomboid!",
            "Also try World of Goo!",
            "Also try Limbo!",
            "Also try Pixeljunk Shooter!",
            "Also try Braid!",
            "That's super!",
            "Bread is pain!",
            "Read more books!",
            "Khaaaaaaaaan!",
            "Less addictive than TV Tropes!",
            "More addictive than lemonade!",
            "Bigger than a bread box!",
            "Millions of peaches!",
            "Fnord!",
            "This is my true form!",
            "Totally forgot about Dre!",
            "Don't bother with the clones!",
            "Pumpkinhead!",
            "Hobo humping slobo babe!",
            "Made by Jeb!",
            "Has an ending!",
            "Finally complete!",
            "Feature packed!",
            "Boots with the fur!",
            "Stop, hammertime!",
            "Testificates!",
            "Conventional!",
            "Homeomorphic to a 3-sphere!",
            "Doesn't avoid double negatives!",
            "Place ALL the blocks!",
            "Does barrel rolls!",
            "Meeting expectations!",
            "PC gaming since 1873!",
            "Ghoughpteighbteau tchoghs!",
            "Déjà vu!",
            "Déjà vu!",
            "Got your nose!",
            "Haley loves Elan!",
            "Afraid of the big, black bat!",
            "Doesn't use the U-word!",
            "Child's play!",
            "See you next Friday or so!",
            "From the streets of Södermalm!",
            "150 bpm for 400000 minutes!",
            "Technologic!",
            "Funk soul brother!",
            "Pumpa kungen!",
            "日本ハロー！",
            "한국 안녕하세요!",
            "Helo Cymru!",
            "Cześć Polsko!",
            "你好中国！",
            "Привет Россия!",
            "Γεια σου Ελλάδα!",
            "My life for Aiur!",
            "Lennart lennart = new Lennart();",
            "I see your vocabulary has improved!",
            "Who put it there?",
            "You can't explain that!",
            "if not ok then return end",
            "§1C§2o§3l§4o§5r§6m§7a§8t§9i§ac",
            "§kFUNKY LOL",
            "Big Pointy Teeth!",
            "Bekarton guards the gate!",
            "Mmmph, mmph!",
            "Don't feed avocados to parrots!",
            "Swords for everyone!",
            "Plz reply to my tweet!",
            ".party()!",
            "Take her pillow!",
            "Put that cookie down!",
            "Pretty scary!",
            "I have a suggestion.",
            "Now with extra hugs!",
            "Now Java 8!",
            "Woah.",
            "HURNERJSGER?",
            "What's up, Doc?",
            "Now contains 32 random daily cats!",
            "That's Numberwang!",
            "pls rt",
            "Do you want to join my server?",
            "Put a little fence around it!",
            "Throw a blanket over it!",
            "One day, somewhere in the future, my work will be quoted!",
            "Now with additional stuff!",
            "Extra things!",
            "Yay, puppies for everyone!",
            "So sweet, like a nice bon bon!",
            "Popping tags!",
            "Very influential in its circle!",
            "Now With Multiplayer!",
            "Rise from your grave!",
            "Warning! A huge battleship \"STEVE\" is approaching fast!",
            "Blue warrior shot the food!",
            "Run, coward! I hunger!",
            "Flavor with no seasoning!",
            "Strange, but not a stranger!",
            "Tougher than diamonds, rich like cream!",
            "Getting ready to show!",
            "Getting ready to know!",
            "Getting ready to drop!",
            "Getting ready to shock!",
            "Getting ready to freak!",
            "Getting ready to speak!",
            "It swings, it jives!",
            "Cruising streets for gold!",
            "Take an eggbeater and beat it against a skillet!",
            "Make me a table, a funky table!",
            "Take the elevator to the mezzanine!",
            "Stop being reasonable, this is the Internet!",
            "/give @a hugs 64",
            "This is good for Realms.",
            "Any computer is a laptop if you're brave enough!",
            "Do it all, everything!",
            "Where there is not light, there can spider!",
            "GNU Terry Pratchett",
            "More Digital!",
            "doot doot",
            "Falling with style!",
            "There's no stopping the Trollmaso",
            "Throw yourself at the ground and miss",
            "Rule #1: it's never my fault",
            "Replaced molten cheese with blood?",
            "Absolutely fixed relatively broken coordinates",
            "Boats FTW",
            "Javalicious edition",
            "Should not be played while driving",
            "You're going too fast!",
            "Don't feed chocolate to parrots!",
            "The true meaning of covfefe",
            "An illusion! What are you hiding?",
            "Something's not quite right...",
            "Thank you for the fish!",
            "All rumors are true!",
            "Truly gone fishing!",

            // Splashes only shown on game crashes:
            "Who set us up the TNT?",
            "Everything's going to plan. No, really, that was supposed to happen.",
            "Uh... Did I do that?",
            "Oops.",
            "Why did you do that?",
            "I feel sad now :(",
            "My bad.",
            "I'm sorry, Dave.",
            "I let you down. Sorry :(",
            "On the bright side, I bought you a teddy bear!",
            "Daisy, daisy...",
            "Oh - I know what I did wrong!",
            "Hey, that tickles! Hehehe!",
            "I blame Dinnerbone.",
            "You should try our sister game, Minceraft!",
            "Don't be sad. I'll do better next time, I promise!",
            "Don't be sad, have a hug! <3",
            "I just don't know what went wrong :(",
            "Shall we play a game?",
            "Quite honestly, I wouldn't worry myself about that.",
            "I bet Cylons wouldn't have this problem.",
            "Sorry :(",
            "Surprise! Haha. Well, this is awkward.",
            "Would you like a cupcake?",
            "Hi. I'm Minecraft, and I'm a crashaholic.",
            "Ooh. Shiny.",
            "This doesn't make any sense!",
            "Why is it breaking :(",
            "Don't do that.",
            "Ouch. That hurt :(",
            "You're mean.",
            "This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]",
            "There are four lights!",
            "But it works on my machine.",

            // Splashes based on the 256 Minecraft characters:
            "\u00c0\u00c1\u00c2\u00c8\u00ca\u00cb\u00cd\u00d3\u00d4\u00d5\u00da\u00df\u00e3\u00f5\u011f\u0130",
            "\u0131\u0152\u0153\u015e\u015f\u0174\u0175\u017e\u0207\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
            " !\"#$%&'()*+,-.",
            "/0123456789:;<=>?",
            "@ABCDEFGHIJKLMNO",
            "PQRSTUVWXYZ[\\]^_",
            "`abcdefghijklmno",
            "pqrstuvwxyz{|}~\u0000",
            "\u00c7\u00fc\u00e9\u00e2\u00e4\u00e0\u00e5\u00e7\u00ea\u00eb\u00e8\u00ef\u00ee\u00ec\u00c4\u00c5",
            "\u00c9\u00e6\u00c6\u00f4\u00f6\u00f2\u00fb\u00f9\u00ff\u00d6\u00dc\u00f8\u00a3\u00d8\u00d7\u0192",
            "\u00e1\u00ed\u00f3\u00fa\u00f1\u00d1\u00aa\u00ba\u00bf\u00ae\u00ac\u00bd\u00bc\u00a1\u00ab\u00bb",
            "\u2591\u2592\u2593\u2502\u2524\u2561\u2562\u2556\u2555\u2563\u2551\u2557\u255d\u255c\u255b\u2510",
            "\u2514\u2534\u252c\u251c\u2500\u253c\u255e\u255f\u255a\u2554\u2569\u2566\u2560\u2550\u256c\u2567",
            "\u2568\u2564\u2565\u2559\u2558\u2552\u2553\u256b\u256a\u2518\u250c\u2588\u2584\u258c\u2590\u2580",
            "\u03b1\u03b2\u0393\u03c0\u03a3\u03c3\u03bc\u03c4\u03a6\u0398\u03a9\u03b4\u221e\u2205\u2208\u2229",
            "\u2261\u00b1\u2265\u2264\u2320\u2321\u00f7\u2248\u00b0\u2219\u00b7\u221a\u207f\u00b2\u25a0\u0000"
        };
    }
}
